LOADING THE LIBRARIES FIRST

In [213]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import accuracy_score,r2_score,mean_squared_error,mean_absolute_error

LOADING THE DATASET

In [214]:
df=pd.read_csv("C:/Users/aniru/Downloads/Dataset .csv")

In [215]:
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [216]:
df.shape

(9551, 21)

ROWS-9551
COLUMNS-21

In [217]:
df.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

DESCRIBE GIVES A STATISTICAL INSIGHT INTO THE DATA

CHECKING FOR NULL VALUES IN THE DATASET

In [218]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

There are no missing values as such

CHECKING FOR DUPLICATE VALUES IN THE DATASET

In [219]:
df[df.duplicated]

Empty DataFrame
Columns: [Restaurant ID, Restaurant Name, Country Code, City, Address, Locality, Locality Verbose, Longitude, Latitude, Cuisines, Average Cost for two, Currency, Has Table booking, Has Online delivery, Is delivering now, Switch to order menu, Price range, Aggregate rating, Rating color, Rating text, Votes]
Index: []

[0 rows x 21 columns]

ENCODING THE CATEGORICAL VARIABLES

In [220]:
cols=["Restaurant Name","City","Address","Locality","Locality Verbose","Cuisines","Average Cost for two","Currency","Has Table booking","Has Online delivery","Is delivering now","Switch to order menu","Rating color","Rating text"]
le=LabelEncoder()
d=df.copy()
for i in cols:
 df[i]=le.fit_transform(df[i])
 print(df)

      Restaurant ID  Restaurant Name  Country Code              City  \
0           6317637             3748           162       Makati City
1           6304287             3172           162       Makati City
2           6300002             2896           162  Mandaluyong City
3           6318506             4707           162  Mandaluyong City
4           6314302             5523           162  Mandaluyong City
...             ...              ...           ...               ...
9546        5915730             4443           208         ��stanbul
9547        5908749             1310           208         ��stanbul
9548        5915807             3068           208         ��stanbul
9549        5916112              512           208         ��stanbul
9550        5927402             7240           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]
      Restaurant ID  Restaurant Name  Country Code  City  \
0           6317637             3748           162    73
1           6304287             3172           162    73
2           6300002             2896           162    75
3           6318506             4707           162    75
4           6314302             5523           162    75
...             ...              ...           ...   ...
9546        5915730             4443           208   140
9547        5908749             1310           208   140
9548        5915807             3068           208   140
9549        5916112              512           208   140
9550        5927402             7240           208   140

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]
      Restaurant ID  Restaurant Name  Country Code  City  Address  \
0           6317637             3748           162    73     8685
1           6304287             3172           162    73     6055
2           6300002             2896           162    75     4684
3           6318506             4707           162    75     8690
4           6314302             5523           162    75     8689
...             ...              ...           ...   ...      ...
9546        5915730             4443           208   140     5926
9547        5908749             1310           208   140     5962
9548        5915807             3068           208   140     5966
9549        5916112              512           208   140     5967
9550        5927402             7240           208   140     4258

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]
      Restaurant ID  Restaurant Name  Country Code  City  Address  Locality  \
0           6317637             3748           162    73     8685       171
1           6304287             3172           162    73     6055       593
2           6300002             2896           162    75     4684       308
3           6318506             4707           162    75     8690       862
4           6314302             5523           162    75     8689       862
...             ...              ...           ...   ...      ...       ...
9546        5915730             4443           208   140     5926       517
9547        5908749             1310           208   140     5962       552
9548        5915807             3068           208   140     5966       554
9549        5916112              512           208   140     5967       554
9550        5927402             7240           208   140     4258       670

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green

We are done with encoding the categorical variables and handling missing values

Let us now seperate the data into predictors and response

In [221]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [222]:
X=df.drop(columns="Cuisines",axis=1)
Y=df["Cuisines"]

In [223]:
print(X)

      Restaurant ID  Restaurant Name  Country Code  City  Address  Locality  \
0           6317637             3748           162    73     8685       171
1           6304287             3172           162    73     6055       593
2           6300002             2896           162    75     4684       308
3           6318506             4707           162    75     8690       862
4           6314302             5523           162    75     8689       862
...             ...              ...           ...   ...      ...       ...
9546        5915730             4443           208   140     5926       517
9547        5908749             1310           208   140     5962       552
9548        5915807             3068           208   140     5966       554
9549        5916112              512           208   140     5967       554
9550        5927402             7240           208   140     4258       670

      Locality Verbose   Longitude   Latitude  Average Cost for two  Currency  \
0                  172  121.027535  14.565443                    73         0
1                  601  121.014101  14.553708                    75         0
2                  314  121.056831  14.581404                   113         0
3                  875  121.056475  14.585318                    81         0
4                  875  121.057508  14.584450                    81         0
...                ...         ...        ...                   ...       ...
9546               523   28.977392  41.022793                    16        11
9547               558   29.041297  41.009847                    21        11
9548               561   29.034640  41.055817                    29        11
9549               561   29.036019  41.057979                    23        11
9550               681   29.026016  40.984776                    11        11

      Has Table booking  Has Online delivery  Is delivering now  \
0                     1                    0                  0
1                     1                    0                  0
2                     1                    0                  0
3                     0                    0                  0
4                     1                    0                  0
...                 ...                  ...                ...
9546                  0                    0                  0
9547                  0                    0                  0
9548                  0                    0                  0
9549                  0                    0                  0
9550                  0                    0                  0

      Switch to order menu  Price range  Aggregate rating  Rating color  \
0                        0            3               4.8             0
1                        0            3               4.5             0
2                        0            4               4.4             1
3                        0            4               4.9             0
4                        0            4               4.8             0
...                    ...          ...               ...           ...
9546                     0            3               4.1             1
9547                     0            3               4.2             1
9548                     0            4               3.7             5
9549                     0            4               4.0             1
9550                     0            2               4.0             1

      Rating text  Votes
0               1    314
1               1    591
2               5    270
3               1    365
4               1    229
...           ...    ...
9546            5    788
9547            5   1034
9548            2    661
9549            5    901
9550            5    591

[9551 rows x 20 columns]

In [224]:
print(Y)

0        920
1       1111
2       1671
3       1126
4       1122
        ...
9546    1813
9547    1824
9548    1110
9549    1657
9550     331
Name: Cuisines, Length: 9551, dtype: int64

Now let us split the data into training data and test data

In [225]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.1,random_state=42)

In [226]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(9551, 20)
(8595, 20)
(956, 20)

In [227]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

We see that the data has already been divided into training data and test data

MODEL CREATION AND TRAINING THE MODEL USING TRAINED DATA

In [228]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
lr = RandomForestClassifier(n_estimators=200,max_depth=15,min_samples_split=5,min_samples_leaf=2,class_weight='balanced',random_state=42,n_jobs=1)
lr.fit(X_train, Y_train)

RandomForestClassifier(class_weight='balanced', max_depth=15,
                       min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, n_jobs=1, random_state=42)

In [229]:
Y_predicted=lr.predict(X_train)

ACCURACY SCORES

In [230]:
accuracy=accuracy_score(Y_train,Y_predicted)
accuracy

0.22524723676556138

In [231]:
Y_predictedtest=lr.predict(X_test)

In [232]:
accuracy_test=accuracy_score(Y_test,Y_predictedtest)
accuracy_test

0.009414225941422594

In [236]:
from sklearn.metrics import precision_score
precision=precision_score(Y_test,Y_predictedtest,average="macro")

c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

creating confusion matrix

In [234]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_predictedtest)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(575, 575))

CLASSIFICATION REPORT

In [235]:
from sklearn.metrics import classification_report
classification_report(Y_test,Y_predictedtest)

c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aniru\OneDrive\Desktop\chandrani\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00         0\n           2       0.00      0.00      0.00         0\n           4       0.00      0.00      0.00         0\n           6       0.00      0.00      0.00         2\n           8       0.00      0.00      0.00         1\n          11       0.00      0.00      0.00         1\n          12       0.00      0.00      0.00         1\n          16       0.00      0.00      0.00         1\n          24       0.00      0.00      0.00         0\n          26       0.00      0.00      0.00         0\n          27       0.00      0.00      0.00         1\n          29       0.00      0.00      0.00         1\n          32       0.00      0.00      0.00         0\n          33       0.00      0.00      0.00         0\n          35       0.00      0.00      0.00         1\n          38       0.00      0.00      0.00         1\n          39       0.00      0.00      0.00         0\n          54       0.00      0.00      0.00         2\n          55       0.00      0.00      0.00         1\n          58       0.00      0.00      0.00         3\n          59       0.00      0.00      0.00         0\n          61       0.00      0.00      0.00         0\n          64       0.00      0.00      0.00         0\n          66       0.00      0.00      0.00         0\n          69       0.00      0.00      0.00         0\n          78       0.00      0.00      0.00         0\n          80       0.00      0.00      0.00         0\n          84       0.00      0.00      0.00         1\n          86       0.00      0.00      0.00         0\n         101       0.00      0.00      0.00         1\n         102       0.00      0.00      0.00         1\n         104       0.00      0.00      0.00         1\n         106       0.00      0.00      0.00         0\n         107       0.00      0.00      0.00         0\n         109       0.00      0.00      0.00         0\n         113       0.00      0.00      0.00         0\n         115       0.00      0.00      0.00         4\n         120       0.00      0.00      0.00         1\n         122       0.00      0.00      0.00         1\n         123       0.00      0.00      0.00         1\n         129       0.00      0.00      0.00         0\n         130       0.00      0.00      0.00         0\n         132       0.00      0.00      0.00         0\n         136       0.00      0.00      0.00         1\n         138       0.00      0.00      0.00         0\n         149       0.00      0.00      0.00         0\n         150       0.00      0.00      0.00         0\n         152       0.00      0.00      0.00         1\n         157       0.00      0.00      0.00         0\n         164       0.00      0.00      0.00         0\n         166       0.00      0.00      0.00         0\n         169       0.00      0.00      0.00         0\n         172       0.00      0.00      0.00         1\n         177       0.00      0.00      0.00        19\n         181       0.00      0.00      0.00         1\n         183       0.00      0.00      0.00         1\n         186       0.00      0.00      0.00        14\n         191       0.00      0.00      0.00         7\n         201       0.00      0.00      0.00        10\n         202       0.00      0.00      0.00         0\n         204       0.00      0.00      0.00         1\n         205       0.00      0.00      0.00         0\n         209       0.00      0.00      0.00         1\n         210       0.00      0.00      0.00         0\n         211       0.00      0.00      0.00         1\n         212       0.00      0.00      0.00         0\n         213       0.00      0.00      0.00         1\n         214       0.00      0.00      0.00         1\n         216       0.00      0.00      0.00         0\n         217       0.00      0.00      0.00         2\n         218       0.00      0.00      0.00         1\n         226       0.00      0.00      0.00         1\n         229       0.00      0.00      0.00         1\n         230       0.00      0.00      0.00         5\n         233       0.00      0.00      0.00         3\n         234       0.00      0.00      0.00         1\n         235       0.00      0.00      0.00         1\n         236       0.00      0.00      0.00         0\n         238       0.00      0.00      0.00         0\n         239       0.00      0.00      0.00         1\n         242       0.00      0.00      0.00         1\n         243       0.00      0.00      0.00         5\n         246       0.00      0.00      0.00         2\n         249       0.00      0.00      0.00         1\n         250       0.00      0.00      0.00         0\n         251       0.00      0.00      0.00         2\n         252       0.00      0.00      0.00         1\n         254       0.00      0.00      0.00         1\n         258       1.00      1.00      1.00         1\n         259       0.00      0.00      0.00         1\n         262       0.00      0.00      0.00         0\n         269       0.00      0.00      0.00         1\n         270       0.00      0.00      0.00         1\n         271       0.00      0.00      0.00         1\n         272       0.00      0.00      0.00         2\n         282       0.00      0.00      0.00         1\n         284       0.00      0.00      0.00         0\n         286       0.00      0.00      0.00         1\n         288       0.00      0.00      0.00         1\n         291       0.00      0.00      0.00         1\n         292       0.00      0.00      0.00         0\n         294       0.00      0.00      0.00         1\n         302       0.00      0.00      0.00         0\n         304       0.00      0.00      0.00         0\n         307       0.00      0.00      0.00         1\n         310       0.00      0.00      0.00         4\n         313       0.00      0.00      0.00         0\n         314       0.00      0.00      0.00         1\n         315       0.00      0.00      0.00         0\n         317       0.00      0.00      0.00         0\n         322       0.00      0.00      0.00         1\n         329       0.00      0.00      0.00         1\n         331       0.00      0.00      0.00        35\n         333       0.00      0.00      0.00         0\n         335       0.00      0.00      0.00         0\n         337       0.00      0.00      0.00         0\n         340       0.00      0.00      0.00         0\n         344       0.00      0.00      0.00         1\n         345       0.00      0.00      0.00         1\n         346       0.00      0.00      0.00         1\n         347       0.00      0.00      0.00         0\n         351       0.00      0.00      0.00         0\n         354       0.00      0.00      0.00         0\n         358       0.00      0.00      0.00         1\n         359       0.00      0.00      0.00         1\n         360       0.00      0.00      0.00         1\n         362       0.00      0.00      0.00         0\n         365       0.00      0.00      0.00         0\n         370       0.00      0.00      0.00         1\n         380       0.00      0.00      0.00         0\n         383       0.00      0.00      0.00         0\n         384       0.00      0.00      0.00         1\n         387       0.00      0.00      0.00         0\n         388       0.00      0.00      0.00         1\n         390       0.00      0.00      0.00         0\n         394       0.00      0.00      0.00         0\n         395       0.00      0.00      0.00         1\n         397       0.00      0.00      0.00         1\n         399       0.00      0.00      0.00         1\n         408       0.00      0.00      0.00         0\n         410       0.00      0.00      0.00         1\n         412       0.00      0.00      0.00         2\n         416       0.00      0.00      0.00         1\n         422       0.00      0.00      0.00         1\n         425       0.00      0.00      0.00         0\n         426       0.00      0.00      0.00         1\n         433       0.00      0.00      0.00         2\n         435       0.00      0.00      0.00         0\n         442       0.00      0.00      0.00         1\n         443       0.00      0.00      0.00         0\n         446       0.00      0.00      0.00         0\n         447       0.00      0.00      0.00         1\n         452       0.00      0.00      0.00         0\n         455       0.00      0.00      0.00         1\n         458       0.00      0.00      0.00         0\n         459       0.00      0.00      0.00         0\n         461       0.00      0.00      0.00         0\n         465       0.00      0.00      0.00         1\n         477       0.00      0.00      0.00         0\n         479       0.00      0.00      0.00         1\n         490       0.00      0.00      0.00         0\n         497       0.00      0.00      0.00        26\n         499       0.00      0.00      0.00         0\n         500       0.00      0.00      0.00         1\n         505       0.00      0.00      0.00         1\n         508       0.00      0.00      0.00         0\n         509       0.00      0.00      0.00         1\n         510       0.00      0.00      0.00         0\n         512       0.00      0.00      0.00         2\n         517       0.00      0.00      0.00         0\n         518       0.00      0.00      0.00        10\n         528       0.00      0.00      0.00         0\n         539       0.00      0.00      0.00         0\n         540       0.00      0.00      0.00         0\n         545       0.00      0.00      0.00         1\n         546       0.00      0.00      0.00         3\n         549       0.00      0.00      0.00         7\n         555       0.00      0.00      0.00         1\n         563       0.00      0.00      0.00         1\n         564       0.00      0.00      0.00         1\n         565       0.00      0.00      0.00         1\n         568       0.00      0.00      0.00         1\n         570       0.00      0.00      0.00         0\n         572       0.00      0.00      0.00         0\n         579       0.00      0.00      0.00         0\n         580       0.00      0.00      0.00         0\n         581       0.00      0.00      0.00         1\n         582       0.00      0.00      0.00         1\n         583       0.00      0.00      0.00         1\n         588       0.00      0.00      0.00         7\n         589       0.00      0.00      0.00         1\n         590       0.00      0.00      0.00         0\n         591       0.00      0.00      0.00         2\n         601       0.00      0.00      0.00         1\n         604       0.00      0.00      0.00         2\n         608       0.00      0.00      0.00         0\n         611       0.00      0.00      0.00         0\n         613       0.00      0.00      0.00         1\n         617       0.00      0.00      0.00         0\n         623       0.00      0.00      0.00         1\n         624       0.00      0.00      0.00         1\n         625       0.00      0.00      0.00         3\n         626       0.00      0.00      0.00         1\n         627       0.00      0.00      0.00         1\n         632       0.00      0.00      0.00         0\n         636       0.00      0.00      0.00         1\n         642       0.00      0.00      0.00         0\n         650       0.00      0.00      0.00         0\n         652       0.00      0.00      0.00         1\n         654       0.00      0.00      0.00         0\n         660       0.00      0.00      0.00         1\n         662       0.00      0.00      0.00         0\n         666       0.00      0.00      0.00         1\n         679       0.00      0.00      0.00         0\n         691       0.00      0.00      0.00         1\n         692       0.00      0.00      0.00         0\n         697       0.00      0.00      0.00         1\n         711       0.00      0.00      0.00         0\n         713       0.00      0.00      0.00         1\n         716       0.00      0.00      0.00         0\n         717       0.00      0.00      0.00         0\n         719       0.00      0.00      0.00         3\n         722       0.00      0.00      0.00         1\n         731       0.00      0.00      0.00         0\n         737       0.00      0.00      0.00         1\n         738       0.00      0.00      0.00         0\n         739       0.00      0.00      0.00         1\n         740       0.00      0.00      0.00         0\n         748       0.00      0.00      0.00         0\n         751       0.00      0.00      0.00         0\n         753       0.00      0.00      0.00         1\n         758       0.00      0.00      0.00         5\n         759       0.00      0.00      0.00         0\n         760       0.00      0.00      0.00         2\n         761       0.00      0.00      0.00         0\n         765       0.00      0.00      0.00         2\n         767       0.00      0.00      0.00         1\n         768       0.00      0.00      0.00         0\n         774       0.00      0.00      0.00         2\n         776       0.00      0.00      0.00         0\n         778       0.00      0.00      0.00         1\n         787       0.00      0.00      0.00         0\n         788       0.00      0.00      0.00         1\n         790       0.00      0.00      0.00         1\n         791       0.00      0.00      0.00         1\n         794       0.00      0.00      0.00         0\n         797       0.00      0.00      0.00         0\n         801       0.00      0.00      0.00         0\n         803       0.00      0.00      0.00         0\n         808       0.00      0.00      0.00         1\n         810       0.00      0.00      0.00         2\n         817       0.00      0.00      0.00         0\n         827       0.00      0.00      0.00         1\n         828       0.00      0.00      0.00        38\n         830       0.00      0.00      0.00         0\n         831       0.00      0.00      0.00         1\n         832       0.00      0.00      0.00         0\n         833       0.00      0.00      0.00         3\n         834       0.00      0.00      0.00         3\n         837       0.00      0.00      0.00         6\n         841       0.00      0.00      0.00         5\n         843       0.00      0.00      0.00         1\n         851       0.00      0.00      0.00         0\n         854       0.00      0.00      0.00         1\n         855       0.00      0.00      0.00         0\n         859       0.00      0.00      0.00         1\n         864       0.00      0.00      0.00         0\n         865       1.00      0.20      0.33         5\n         873       0.00      0.00      0.00         0\n         874       0.00      0.00      0.00         1\n         882       0.00      0.00      0.00         1\n         886       0.00      0.00      0.00         1\n         887       0.00      0.00      0.00         1\n         888       0.00      0.00      0.00         1\n         894       1.00      1.00      1.00         1\n         895       0.00      0.00      0.00         6\n         896       0.00      0.00      0.00         0\n         898       0.00      0.00      0.00         1\n         899       0.00      0.00      0.00         1\n         903       0.00      0.00      0.00         0\n         907       0.00      0.00      0.00         0\n         909       0.00      0.00      0.00         1\n         913       0.00      0.00      0.00         2\n         914       0.00      0.00      0.00         1\n         916       0.00      0.00      0.00         1\n         919       0.00      0.00      0.00         1\n         920       0.00      0.00      0.00         1\n         921       0.00      0.00      0.00         1\n         928       0.00      0.00      0.00         1\n         929       0.00      0.00      0.00         0\n         931       0.00      0.00      0.00         1\n         933       0.00      0.00      0.00         0\n         934       0.00      0.00      0.00         1\n         936       0.00      0.00      0.00         0\n         941       0.00      0.00      0.00         1\n         942       0.00      0.00      0.00         0\n         947       0.00      0.00      0.00         1\n         951       0.00      0.00      0.00         1\n         953       0.00      0.00      0.00         1\n         955       0.00      0.00      0.00         1\n         962       0.00      0.00      0.00         0\n         965       0.00      0.00      0.00         0\n         967       0.00      0.00      0.00         1\n         972       0.00      0.00      0.00         1\n         975       0.00      0.00      0.00         1\n         977       0.00      0.00      0.00         0\n         978       0.00      0.00      0.00         1\n         980       0.00      0.00      0.00         1\n         982       0.00      0.00      0.00         9\n         986       0.00      0.00      0.00         5\n         993       0.00      0.00      0.00         1\n         995       0.00      0.00      0.00         2\n         996       0.00      0.00      0.00         0\n        1015       0.00      0.00      0.00         0\n        1017       0.00      0.00      0.00         0\n        1018       0.00      0.00      0.00         1\n        1020       0.00      0.00      0.00         1\n        1030       0.00      0.00      0.00         1\n        1031       0.00      0.00      0.00         8\n        1039       0.00      0.00      0.00         0\n        1040       0.00      0.00      0.00         1\n        1042       0.00      0.00      0.00         0\n        1044       0.00      0.00      0.00         1\n        1050       0.00      0.00      0.00         1\n        1051       0.00      0.00      0.00         1\n        1052       0.00      0.00      0.00         0\n        1055       0.00      0.00      0.00         0\n        1058       0.00      0.00      0.00         0\n        1059       0.00      0.00      0.00         1\n        1063       0.00      0.00      0.00         1\n        1065       0.00      0.00      0.00         2\n        1066       0.00      0.00      0.00         0\n        1068       0.00      0.00      0.00         1\n        1070       0.00      0.00      0.00         0\n        1072       0.00      0.00      0.00         1\n        1075       0.00      0.00      0.00         0\n        1080       0.00      0.00      0.00         0\n        1081       0.00      0.00      0.00         1\n        1083       0.00      0.00      0.00         0\n        1084       0.00      0.00      0.00         1\n        1089       0.00      0.00      0.00         0\n        1094       0.00      0.00      0.00         1\n        1098       0.00      0.00      0.00         1\n        1101       0.00      0.00      0.00         0\n        1102       0.00      0.00      0.00         6\n        1107       0.00      0.00      0.00         0\n        1111       0.00      0.00      0.00         3\n        1112       0.00      0.00      0.00         0\n        1115       0.00      0.00      0.00         1\n        1116       0.00      0.00      0.00         2\n        1122       0.00      0.00      0.00         2\n        1126       0.00      0.00      0.00         2\n        1135       0.00      0.00      0.00         2\n        1137       0.00      0.00      0.00         0\n        1138       0.00      0.00      0.00         1\n        1140       0.00      0.00      0.00         1\n        1142       0.00      0.00      0.00         0\n        1144       0.00      0.00      0.00         1\n        1151       0.00      0.00      0.00         0\n        1153       0.00      0.00      0.00         1\n        1155       0.00      0.00      0.00         0\n        1157       0.00      0.00      0.00         1\n        1158       0.00      0.0